### ISSUE TITLE
Add contribution guidelines and how-to

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/site#38]
- [ ] document how to submit something to the wiki
- [x] add some inclusion standard maybe (`CONTRIBUTING.md`)

This has been requested by @Croydon (ping) but will benefit everybody 👍

**Comment by Croydon** [comment]
https://github.com/inexorgame/blog-data#blog-data

**Comment by MartinMuzatko** [comment]
I am a bit torn about where to include the info.
`CONTRIBUTING.md` is not automatically included in the website. It would be nice to have the information in the wiki as well. Or we can link to the contributing file from within the wiki. 
What do you think @Fohlen ?

**Comment by Fohlen** [comment]
@MartinMuzatko I believe that's the best way of doing it. Move the old README to `CONTRIBUTING.md` and link to that from the wiki
