### ISSUE TITLE
Ingame wiki / faq / knowledgebase

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/site#45]
_From @Fohlen on December 5, 2015 20:7_

We could render an in-game wiki on the website with markdown.
The files should go into `blog-data` and could also be available in the game using a NodeJS/markdown-renderer.
On our websites there should be a sort of knowledge-base, searchable with Ajax

_Copied from original issue: inexor-game/website#30_

**Comment by IAmNotHanni** [comment]
The new wiki in vulkan-renderer repo will contain all information we need.
This ticket is deprecated: https://github.com/inexorgame/site/issues/75
