### ISSUE TITLE
get involved contains archived issue links

### ISSUE THREAD

**Issue by GamesOpenSource** [inexorgame/site#56]
https://github.com/inexorgame/site/blob/d731f65bbf1bcaa38e4312ccebd62b87113b4283/content/wiki/Get-Involved.md

"Voice Acting" link links to https://github.com/inexorgame/inexor-core/issues/255 which is "This repository has been archived by the owner. It is now read-only."

**Comment by IAmNotHanni** [comment]
@GamesOpenSource Thank you for this ticket (a little late in response sry).
This will be resolved by our new wiki: https://github.com/inexorgame/site/issues/75.
This issue is therefore deprecated.
