### ISSUE TITLE
Rework Team page

### ISSUE THREAD

**Issue by MartinMuzatko** [inexorgame/site#63]
The team page is currently automatically rendered using github information.
I would like to replace it with a manual list with respect to the field of work everyone has contributed so far.

This is a manual process so the list has to be maintained. 

@inexorgame/members  PLEASE let me know what on the website you would like to be listed as.
Like what kind of work you have contributed, and what your interests are - a tiny bio ~1-2 sentences.

I will also create a section for our previous members that have contributed their ideas, code and content.
If you want to be listed, please also let me know. These are the ones that I know of:

@Fohlen 
@terencode 
@Croydon

**Comment by terencode** [comment]
Thanks, I'd appreciate as well, probably with something along "website design contribution".
